# build docker
# publish to container registry
# build helm
# publish to helm repo

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - None

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'bc2aadcc-1517-44b8-9314-ea3f6c496a86'
  imageRepository: 'bpdataservice'
  containerRegistry: 'ainhabacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  azureACRSubscription: '7263e463-da66-4888-a897-f34f5acea14b'
  azureACRResourceGroup: 'k8s-resource-group'
  tag: 'v1'


steps:
#  - task: NodeTool@0
#    inputs:
#      versionSource: 'spec'
#      versionSpec: '6.x'
#    displayName: 'Installing nodejs as a pre-requiste for unittest'
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)
  # Package and deploy Helm charts v0
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Azure Resource Manager'
      # Azure Container Registry
      azureSubscriptionForACR: ${azureACRSubscription}
      azureResourceGroupForACR: ${azureACRResourceGroup}
      azureContainerRegistry: ${containerRegistry}
      # Commands
      command: 'package'
      chartType: 'FilePath'
      chartPath: $(Build.SourcesDirectory)/helm
      save: true