apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdata-app
  labels:
    app: bpdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdata
  template:
    metadata:
      labels:
        app: bpdata
    spec:
      volumes:
        - name: mongo-secrets
          secret:
            secretName: mongo-secrets
            items:
              - key: MONGO_CREDENTIAL
                path: MONGO_CREDENTIAL
                mode: 0444
      containers:
        - image: bpdataservice:CA2_TEST_V1
          name: bpdataapp
          imagePullPolicy: Never
          ports:
            - containerPort: 43256
          env:
            - name: PROFILE
              value: "production"
          volumeMounts:
            - name: mongo-secrets
              mountPath: /etc/mongo-secrets
              readOnly: true
