apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: bpdatasvc
spec:
  # Add external load balancer
  # *Only supported by some cloud providers*
  type: ClusterIP
  ports:
    - name: http
      port: 43256
      targetPort: 43256
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: bpdata